{
  description = "Declarative Home Configuration";

  inputs = {
    # Nix Packages collection (stick to the latest stable release for better cache hits)
    nixpkgs.url = "github:nixos/nixpkgs/nixos-24.05";

    # Home Manager for managing user environments
    home-manager = {
      # Track the matching Home Manager release to avoid rebuilding Nix from source
      url = "github:nix-community/home-manager/release-24.05";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # --- ZSH Plugins as Inputs ---
    # Nix tracks the exact commit in flake.lock for reproducibility.
    zsh-syntax-highlighting = {
      url = "github:zsh-users/zsh-syntax-highlighting";
      flake = false; # This is just source code, not a flake
    };

    zsh-autocomplete = {
      url = "github:marlonrichert/zsh-autocomplete";
      flake = false; # This is just source code, not a flake
    };

    fresh.url = "github:sinelaw/fresh/v0.1.67";

    # Local host overrides (generated by bootstrap.sh, defaults to empty module)
    local-host = {
      url = "path:./hosts/default";
      flake = true;
    };

  };

  # The output of the flake
  outputs = { self, nixpkgs, home-manager, ... }@inputs:
    let
      # Define supported systems
      supportedSystems = [ "x86_64-linux" "aarch64-linux" "x86_64-darwin" "aarch64-darwin" ];

      # Helper function to generate attribute sets for all systems
      forAllSystems = nixpkgs.lib.genAttrs supportedSystems;

      # Helper function to create a Home Manager configuration for a given system and user
      # homeDirectory is set via local-host input (overridden by setup.sh at runtime)
      mkHomeConfiguration = system: username:
        let
          # Fallback home directory (used when local-host doesn't override)
          defaultHome = if nixpkgs.lib.hasSuffix "-darwin" system
            then "/Users/${username}"
            else "/home/${username}";
        in
        home-manager.lib.homeManagerConfiguration {
          pkgs = nixpkgs.legacyPackages.${system};
          extraSpecialArgs = { inherit inputs; }; # Pass flake inputs to modules
          modules =
            [
              ./home.nix
              inputs.local-host.homeModules.default  # Machine-specific overrides
              {
                home.username = username;
                home.homeDirectory = nixpkgs.lib.mkDefault defaultHome;
              }
            ];
        };

      # List of users to generate configurations for
      users = [ "julsh" ];

      # Generate all user@system combinations
      userConfigurations = builtins.listToAttrs (
        nixpkgs.lib.flatten (
          map (user:
            map (system: {
              name = "${user}@${system}";
              value = mkHomeConfiguration system user;
            }) supportedSystems
          ) users
        )
      );

    in
    {
      # Expose the generated configurations to home-manager.
      homeConfigurations = userConfigurations;

      # Expose the packaged home-manager CLI for convenience.
      packages = forAllSystems (system: {
        home-manager = home-manager.packages.${system}.home-manager;
      });

      # Make home-manager available as a runnable app for each system.
      apps = forAllSystems (system: {
        default = {
          type = "app";
          program = "${home-manager.packages.${system}.home-manager}/bin/home-manager";
        };
        home-manager = {
          type = "app";
          program = "${home-manager.packages.${system}.home-manager}/bin/home-manager";
        };
      });

      # Dev shell with tools needed for setup scripts
      devShells = forAllSystems (system:
        let pkgs = nixpkgs.legacyPackages.${system};
        in {
          default = pkgs.mkShell {
            packages = with pkgs; [
              coreutils
              gnugrep
              gnused
              findutils
              bash
              curl
              jq
              unzip
            ];
          };
        });
    };
}
