{
  description = "Declarative Home Configuration";

  inputs = {
    # Nix Packages collection (stick to the latest stable release for better cache hits)
    nixpkgs.url = "github:nixos/nixpkgs/nixos-26.05";

    # Home Manager for managing user environments
    home-manager = {
      # Track the matching Home Manager release to avoid rebuilding Nix from source
      url = "github:nix-community/home-manager/release-26.05";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # --- ZSH Plugins as Inputs ---
    # Nix tracks the exact commit in flake.lock for reproducibility.
    zsh-syntax-highlighting = {
      url = "github:zsh-users/zsh-syntax-highlighting";
      flake = false; # This is just source code, not a flake
    };

    zsh-autocomplete = {
      # Pinned to older version - newer versions break atuin's zle widgets
      url = "github:marlonrichert/zsh-autocomplete/bbba73ebdc7c01323e09d4d518e51e2d6847ccc2";
      flake = false; # This is just source code, not a flake
    };

    fresh.url = "github:sinelaw/fresh/v0.4.3";

    # Pinned nixpkgs for atuin 18.12.1 (fixes macOS Tahoe/zsh crash)
    nixpkgs-atuin.url = "github:nixos/nixpkgs/66e918c518991dc4275d94b8e1d87a7d46d67201";

    # Pin the post-release commit whose flake references the stable v9 assets.
    keytap.url = "github:jul-sh/keytap/099f2e1d00bcd999ecd2cd6ad815ff5bc33f3f6f";

    # Local host overrides (generated by bootstrap.sh, defaults to empty module)
    local-host = {
      url = "path:./hosts/default";
      flake = true;
    };

  };

  # The output of the flake
  outputs = { self, nixpkgs, home-manager, ... }@inputs:
    let
      # Define supported systems
      supportedSystems = [ "x86_64-linux" "aarch64-linux" "x86_64-darwin" "aarch64-darwin" ];

      # Helper function to generate attribute sets for all systems
      forAllSystems = nixpkgs.lib.genAttrs supportedSystems;

      # The local-host input replaces these user defaults during setup.
      mkHomeConfiguration = system:
        let
          pkgs = nixpkgs.legacyPackages.${system};
          defaultHome = if nixpkgs.lib.hasSuffix "-darwin" system
            then "/Users/julsh"
            else "/home/julsh";
        in
        home-manager.lib.homeManagerConfiguration {
          inherit pkgs;
          extraSpecialArgs = { inherit inputs; }; # Pass flake inputs to modules
          modules =
            [
              ./home.nix
              inputs.local-host.homeModules.default  # Machine-specific overrides
              {
                home.username = nixpkgs.lib.mkDefault "julsh";
                home.homeDirectory = nixpkgs.lib.mkDefault defaultHome;
              }
            ];
        };

    in
    {
      homeConfigurations = forAllSystems mkHomeConfiguration;

      # Dev shell with tools needed for setup scripts
      devShells = forAllSystems (system:
        let pkgs = nixpkgs.legacyPackages.${system};
        in {
          default = pkgs.mkShell {
            packages = with pkgs; [
              coreutils
              gnugrep
              gnused
              findutils
              bash
              curl
              jq
              unzip
            ] ++ pkgs.lib.optionals pkgs.stdenv.hostPlatform.isDarwin [
              pkgs.swiftPackages.swift
            ];
          };
        });
    };
}
