#!/usr/bin/env bash
# nix/setup-internal.sh - Core setup logic intended to run inside `nix develop`

set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

# --- Helpers ---
die() { echo "error: $1" >&2; exit 1; }

get_nix_system() {
    local os arch
    case "$OSTYPE" in
        linux-gnu*) os="linux" ;;
        darwin*)    os="darwin" ;;
        *)          die "Unsupported OS: $OSTYPE" ;;
    esac
    case "$(uname -m)" in
        x86_64)        arch="x86_64" ;;
        aarch64|arm64) arch="aarch64" ;;
        *)             die "Unsupported arch: $(uname -m)" ;;
    esac
    echo "${arch}-${os}"
}

# =============================================================================
# Main setup (runs inside nix develop with all tools available)
# =============================================================================

ensure_local_host_flake() {
    mkdir -p nix/hosts/local
    cat > nix/hosts/local/flake.nix <<EOF
{
  # Machine-specific overrides (generated by bootstrap.sh)
  outputs = { ... }: {
    homeModules.default = { lib, ... }: {
      home.homeDirectory = lib.mkForce "$HOME";
    };
  };
}
EOF
}

apply_nix_config() {
    echo "Building Home Manager configuration (this may take a few minutes)..."
    ensure_local_host_flake
    local nix_config=$'experimental-features = nix-command flakes\nsubstituters = https://cache.nixos.org/\ntrusted-substituters = https://cache.nixos.org/\n'
    local config_name="${USER}@$(get_nix_system)"
    local local_host_override="--override-input local-host path:./nix/hosts/local"
    # Build the activation package directly (avoids the home-manager CLI
    # and its inetutils dependency which fails to compile on macOS).
    NIX_CONFIG="$nix_config" \
    nix build --no-write-lock-file $local_host_override \
        "./nix#homeConfigurations.\"${config_name}\".activationPackage" \
        --out-link ./result
    ./result/activate
    rm -f ./result
}

install_desktop_apps() {
    if [[ "$OSTYPE" == "linux-gnu"* ]]; then
        command -v zed &>/dev/null || {
            echo "Installing Zed..."
            curl -f https://zed.dev/install.sh | sh
        }
    fi
}

install_cargo_tools() {
    echo "Installing cargo tools..."
    if command -v rustup &>/dev/null; then
        if rustup show | grep -q "no active toolchain"; then
            echo "Setting rustup default toolchain to nightly..."
            rustup default nightly
        fi
    fi
}

setup_local_rc_files() {
    local pairs=".profile:.profile.shared .bash_profile:.profile.shared .bashrc:.bashrc.shared .zprofile:.profile.shared .zshrc:.zshrc.shared"
    local marker="# >>> jul-sh/dotfiles managed block >>>"
    local end_marker="# <<< jul-sh/dotfiles managed block <<<"

    for pair in $pairs; do
        local rc="${pair%%:*}"
        local shared="${pair#*:}"
        local target="${HOME}/${rc}"
        local inject_logic="[ -f \"\${HOME}/${shared}\" ] && . \"\${HOME}/${shared}\""

        if [[ -L "$target" ]] && [[ "$(readlink "$target")" == "$(pwd)/dotfiles/$rc" ]]; then
            local materialized
            materialized=$(mktemp)
            cp -L "$target" "$materialized"
            rm -f "$target"
            mv "$materialized" "$target"
        fi

        [[ -f "$target" ]] && grep -qF "$marker" "$target" && continue
        [[ -f "$target" ]] && echo "Updating ${rc}..." || echo "Creating ${rc}..."

        local tmpfile
        tmpfile=$(mktemp)
        printf '%s\n%s\n%s\n\n' "$marker" "$inject_logic" "$end_marker" > "$tmpfile"
        if [[ -f "$target" ]]; then
            cat "$target" >> "$tmpfile"
        else
            printf '%s\n\n' '# Machine-specific configuration below' >> "$tmpfile"
        fi
        mv "$tmpfile" "$target"
    done
}

symlink_dotfiles() {
    echo "Symlinking dotfiles..."
    local src_dir="dotfiles" repo_dir
    repo_dir=$(pwd)

    git ls-files -z -- "$src_dir" | while IFS= read -r -d '' src; do
        local rel="${src#$src_dir/}"
        local dst="$HOME/$rel"
        local target="$repo_dir/$src"

        # Skip if already correctly symlinked
        if [[ -L "$dst" ]] && [[ "$(readlink "$dst")" == "$target" ]]; then
            continue
        fi

        mkdir -p "$(dirname "$dst")"
        rm -f "$dst"
        ln -s "$target" "$dst"
        echo "  $rel"
    done
}

install_git_hooks() {
    echo "Installing git hooks..."
    mkdir -p .git/hooks
    ln -sf ../../hooks/pre-push .git/hooks/pre-push

    command -v git-lfs &>/dev/null || return 0
    git lfs install --skip-smudge >/dev/null 2>&1
    local git_lfs_path hooks_dir hook
    git_lfs_path=$(command -v git-lfs)
    hooks_dir=$(git config --global core.hooksPath 2>/dev/null || true)
    [[ -d "$hooks_dir" ]] || return 0
    for hook in "$hooks_dir"/{post-checkout,post-commit,post-merge,pre-push}; do
        if [[ -f "$hook" ]]; then
            sed -i.bak "s|command -v git-lfs|command -v $git_lfs_path|g; s|git lfs |$git_lfs_path |g" "$hook"
            rm -f "$hook.bak"
        fi
    done
}

install_nix_custom_conf() {
    local src="./nix/nix.custom.conf"
    local dst="/etc/nix/nix.custom.conf"
    local scope="${SETUP_SCOPE:-}"
    [[ -n "$scope" ]] || [[ ! -f .setup_scope ]] || scope=$(<.setup_scope)
    [[ "${scope:-system}" == system ]] || return 0
    if [[ -f "$src" ]] && ! diff -q "$src" "$dst" &>/dev/null; then
        echo "Installing nix.custom.conf..."
        sudo mkdir -p "$(dirname "$dst")"
        sudo cp "$src" "$dst"
    fi
}

run_setup() {
    install_nix_custom_conf
    apply_nix_config
    symlink_dotfiles
    setup_local_rc_files
    if [[ "$OSTYPE" == "darwin"* ]]; then
        bash ./macos/setup.sh
    else
        install_desktop_apps
    fi
    install_cargo_tools
    if command -v bw &>/dev/null; then
        bw config server https://vault.bitwarden.eu
    fi
    install_git_hooks
    echo "✓ Setup complete. Please restart your terminal for changes to take effect."
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    run_setup
fi
