#!/usr/bin/env bash
# nix/setup-internal.sh - Core setup logic intended to run inside `nix develop`

set -euo pipefail

# Ensure we are in the repo root
cd "$(dirname "$0")/.."

# --- Helpers ---
die() { echo "error: $1" >&2; exit 1; }

get_nix_system() {
    local os arch
    case "$OSTYPE" in
        linux-gnu*) os="linux" ;;
        darwin*)    os="darwin" ;;
        *)          die "Unsupported OS: $OSTYPE" ;;
    esac
    case "$(uname -m)" in
        x86_64)        arch="x86_64" ;;
        aarch64|arm64) arch="aarch64" ;;
        *)             die "Unsupported arch: $(uname -m)" ;;
    esac
    echo "${arch}-${os}"
}

# =============================================================================
# Main setup (runs inside nix develop with all tools available)
# =============================================================================

ensure_local_host_flake() {
    mkdir -p nix/hosts/local
    cat > nix/hosts/local/flake.nix <<EOF
{
  # Machine-specific overrides (generated by bootstrap.sh)
  outputs = { ... }: {
    homeModules.default = { lib, ... }: {
      home.homeDirectory = lib.mkForce "$HOME";
    };
  };
}
EOF
}

apply_nix_config() {
    echo "Applying Home Manager configuration..."
    ensure_local_host_flake
    local nix_config=$'experimental-features = nix-command flakes\nsubstituters = https://cache.nixos.org/\ntrusted-substituters = https://cache.nixos.org/\n'
    local config_name="${USER}@$(get_nix_system)"
    local local_host_override="--override-input local-host path:./nix/hosts/local"
    # Build the activation package directly (avoids the home-manager CLI
    # and its inetutils dependency which fails to compile on macOS).
    NIX_CONFIG="$nix_config" \
    nix build --no-write-lock-file $local_host_override \
        "./nix#homeConfigurations.\"${config_name}\".activationPackage" \
        --out-link ./result
    ./result/activate
    rm -f ./result
}

install_desktop_apps() {
    if [[ "$OSTYPE" == "linux-gnu"* ]]; then
        command -v zed &>/dev/null || {
            echo "Installing Zed..."
            curl -f https://zed.dev/install.sh | sh
        }
    fi
}

install_cargo_tools() {
    echo "Installing cargo tools..."
    if command -v rustup &>/dev/null; then
        if rustup show | grep -q "no active toolchain"; then
            echo "Setting rustup default toolchain to nightly..."
            rustup default nightly
        fi
    fi
}

setup_local_rc_files() {
    local pairs=".profile:.profile.shared .bash_profile:.profile.shared .bashrc:.bashrc.shared .zprofile:.profile.shared .zshrc:.zshrc.shared"

    for pair in $pairs; do
        local rc="${pair%%:*}"
        local shared="${pair#*:}"
        local target="${HOME}/${rc}"

        local env_logic='
# Source .ENV (case invariant) if it exists
if command -v find >/dev/null 2>&1; then
    _env_file=$(find "$HOME" -maxdepth 1 -iname ".env" -type f | head -n 1)
    [ -n "$_env_file" ] && . "$_env_file"
    unset _env_file
fi'

        if [[ -f "$target" ]]; then
            if ! grep -q "Source .ENV" "$target"; then
                echo "Updating ${rc}..."
                echo "$env_logic" >> "$target"
            fi
        else
            echo "Creating ${rc}..."
            cat > "$target" <<EOF
# Source shared configuration (managed by Nix Home Manager)
[ -f "\${HOME}/${shared}" ] && . "\${HOME}/${shared}"

$env_logic

# Machine-specific configuration below

EOF
        fi
    done
}

symlink_dotfiles() {
    echo "Symlinking dotfiles..."
    local src_dir="./dotfiles"
    local repo_dir
    repo_dir=$(pwd)

    # Remove old Nix store symlinks that would redirect writes to source
    # Find all directories in dotfiles/ and check if corresponding $HOME path is a symlink to Nix store
    echo "  Cleaning up old Nix symlinks..."
    find "$src_dir" -type d | while read -r dir; do
        local rel="${dir#$src_dir/}"
        [[ -z "$rel" ]] && continue
        local home_path="$HOME/$rel"
        if [[ -L "$home_path" ]] && readlink "$home_path" | grep -q "^/nix/store"; then
            rm -f "$home_path"
        fi
    done

    # Restore any corrupted source files (symlinks in dotfiles/)
    local corrupted
    corrupted=$(find "$src_dir" -type l 2>/dev/null || true)
    if [[ -n "$corrupted" ]]; then
        echo "  Restoring corrupted source files..."
        while IFS= read -r f; do
            rm -f "$f"
            git checkout HEAD -- "${f#./}" 2>/dev/null || true
        done <<< "$corrupted"
    fi

    find "$src_dir" -type f ! -name "*.backup" ! -name ".DS_Store" | while read -r src; do
        local rel="${src#$src_dir/}"
        local dst="$HOME/$rel"
        local target="${repo_dir}/dotfiles/${rel}"

        # Skip if already correctly symlinked
        if [[ -L "$dst" ]] && [[ "$(readlink "$dst")" == "$target" ]]; then
            continue
        fi

        mkdir -p "$(dirname "$dst")"
        rm -f "$dst"
        ln -s "$target" "$dst"
        echo "  $rel"
    done
}

install_git_hooks() {
    echo "Installing git hooks..."
    mkdir -p .git/hooks
    ln -sf ../../hooks/pre-push .git/hooks/pre-push
}

run_setup() {
    apply_nix_config
    symlink_dotfiles
    setup_local_rc_files
    if [[ "$OSTYPE" == "darwin"* ]]; then
        bash ./macos/setup.sh
    else
        install_desktop_apps
    fi
    install_cargo_tools
    install_git_hooks
    echo "✓ Setup complete. Please restart your terminal for changes to take effect."
}

run_setup
