#!/usr/bin/env bash
# nix/setup-internal.sh - Core setup logic intended to run inside `nix develop`

set -euo pipefail

# Ensure we are in the repo root
cd "$(dirname "$0")/.."

# --- Helpers ---
die() { echo "error: $1" >&2; exit 1; }

get_nix_system() {
    local os arch
    case "$OSTYPE" in
        linux-gnu*) os="linux" ;;
        darwin*)    os="darwin" ;;
        *)          die "Unsupported OS: $OSTYPE" ;;
    esac
    case "$(uname -m)" in
        x86_64)        arch="x86_64" ;;
        aarch64|arm64) arch="aarch64" ;;
        *)             die "Unsupported arch: $(uname -m)" ;;
    esac
    echo "${arch}-${os}"
}

# =============================================================================
# Main setup (runs inside nix develop with all tools available)
# =============================================================================

ensure_local_host_flake() {
    mkdir -p nix/hosts/local
    cat > nix/hosts/local/flake.nix <<EOF
{
  # Machine-specific overrides (generated by bootstrap.sh)
  outputs = { ... }: {
    homeModules.default = { lib, ... }: {
      home.homeDirectory = lib.mkForce "$HOME";
    };
  };
}
EOF
}

apply_nix_config() {
    echo "Applying Home Manager configuration..."
    ensure_local_host_flake
    local nix_config=$'experimental-features = nix-command flakes\nsubstituters = https://cache.nixos.org/\ntrusted-substituters = https://cache.nixos.org/\n'
    local flake_ref="./nix#${USER}@$(get_nix_system)"
    local local_host_override="--override-input local-host path:./nix/hosts/local"
    NIX_CONFIG="$nix_config" \
    nix run --no-write-lock-file $local_host_override "./nix#home-manager" -- \
        switch --flake "$flake_ref" --no-write-lock-file $local_host_override -b backup
}

check_app_updates() {
    local lockfile="./external.lock.json"

    local locked_wezterm
    locked_wezterm=$(jq -r '.wezterm.version' "$lockfile")
    local latest_wezterm
    latest_wezterm=$(curl -fsSL "https://api.github.com/repos/wez/wezterm/releases/latest" 2>/dev/null | jq -r '.tag_name' || echo "$locked_wezterm")
    if [[ "$latest_wezterm" != "$locked_wezterm" ]]; then
        echo "warning: WezTerm $latest_wezterm available (locked: $locked_wezterm). Run ./update.sh to update."
    fi

    local locked_zed
    locked_zed=$(jq -r '.zed.version' "$lockfile")
    local latest_zed
    latest_zed=$(curl -fsSL "https://api.github.com/repos/zed-industries/zed/releases/latest" 2>/dev/null | jq -r '.tag_name' || echo "$locked_zed")
    if [[ "$latest_zed" != "$locked_zed" ]]; then
        echo "warning: Zed $latest_zed available (locked: $locked_zed). Run ./update.sh to update."
    fi
}

quit_app_if_running() {
    local app_name="$1"
    if pgrep -x "$app_name" >/dev/null; then
        echo "  Quitting $app_name..."
        osascript -e "quit app \"$app_name\"" 2>/dev/null || true
        sleep 1
    fi
}

install_app_from_zip() {
    local url="$1" expected_sha256="$2" app_name="$3"
    local tmp_dir zip_path actual_sha256

    tmp_dir="$(mktemp -d)"
    zip_path="${tmp_dir}/app.zip"

    curl -fsSL "$url" -o "$zip_path"
    actual_sha256=$(shasum -a 256 "$zip_path" | awk '{print $1}')
    if [[ "$actual_sha256" != "$expected_sha256" ]]; then
        rm -rf "$tmp_dir"
        die "SHA256 mismatch for $app_name: expected $expected_sha256, got $actual_sha256"
    fi

    unzip -q "$zip_path" -d "$tmp_dir"
    local app_bundle
    app_bundle=$(find "$tmp_dir" -name "*.app" -type d | head -1)
    if [[ -z "$app_bundle" ]]; then
        echo "Contents of extracted zip:"
        ls -la "$tmp_dir"
        rm -rf "$tmp_dir"
        die "No .app bundle found in $app_name zip file"
    fi
    quit_app_if_running "$app_name"
    sudo rm -rf "/Applications/${app_name}.app"
    sudo mv "$app_bundle" "/Applications/${app_name}.app"
    sudo xattr -dr com.apple.quarantine "/Applications/${app_name}.app" 2>/dev/null || true

    rm -rf "$tmp_dir"
}

install_app_from_dmg() {
    local url="$1" expected_sha256="$2" app_name="$3"
    local tmp_dir dmg_path actual_sha256 mount_point

    tmp_dir="$(mktemp -d)"
    dmg_path="${tmp_dir}/app.dmg"

    curl -fsSL "$url" -o "$dmg_path"
    actual_sha256=$(shasum -a 256 "$dmg_path" | awk '{print $1}')
    if [[ "$actual_sha256" != "$expected_sha256" ]]; then
        rm -rf "$tmp_dir"
        die "SHA256 mismatch for $app_name: expected $expected_sha256, got $actual_sha256"
    fi

    mount_point=$(hdiutil attach -nobrowse -readonly "$dmg_path" 2>/dev/null | grep -o '/Volumes/.*' | head -1)
    local app_bundle
    app_bundle=$(find "$mount_point" -maxdepth 1 -name "*.app" | head -1)
    quit_app_if_running "$app_name"
    sudo rm -rf "/Applications/${app_name}.app"
    sudo cp -R "$app_bundle" "/Applications/${app_name}.app"
    sudo xattr -dr com.apple.quarantine "/Applications/${app_name}.app" 2>/dev/null || true
    hdiutil detach "$mount_point" -quiet

    rm -rf "$tmp_dir"
}

install_desktop_apps() {
    local lockfile="./external.lock.json"

    if [[ "$OSTYPE" == "darwin"* ]]; then
        echo "Installing desktop apps..."
        check_app_updates

        local arch
        arch=$(uname -m)
        [[ "$arch" == "arm64" ]] && arch="aarch64"

        local wezterm_url wezterm_sha256
        wezterm_url=$(jq -r '.wezterm.url' "$lockfile")
        wezterm_sha256=$(jq -r '.wezterm.sha256' "$lockfile")
        echo "  Installing WezTerm..."
        install_app_from_zip "$wezterm_url" "$wezterm_sha256" "WezTerm"

        local zed_url zed_sha256
        zed_url=$(jq -r ".zed.${arch}.url" "$lockfile")
        zed_sha256=$(jq -r ".zed.${arch}.sha256" "$lockfile")
        echo "  Installing Zed..."
        install_app_from_dmg "$zed_url" "$zed_sha256" "Zed"

        install_clipkitty
    elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
        command -v zed &>/dev/null || {
            echo "Installing Zed..."
            curl -f https://zed.dev/install.sh | sh
        }
    fi
}

install_clipkitty() {
    local lockfile="./external.lock.json"
    local url sha256
    url=$(jq -r '.clipkitty.url' "$lockfile")
    sha256=$(jq -r '.clipkitty.sha256' "$lockfile")
    echo "  Installing ClipKitty..."
    install_app_from_zip "$url" "$sha256" "ClipKitty"
}

build_spotlight_scripts() {
    [[ "$OSTYPE" == "darwin"* ]] || return 0
    local script="./macos/raycast_scripts/build_spotlight_apps.sh"
    if [[ -f "$script" ]]; then
        echo "Building Spotlight apps..."
        bash "$script"
    fi
}

install_fonts() {
    echo "Installing fonts..."
    local lockfile="./external.lock.json"
    local target_dir

    if [[ "$OSTYPE" == "darwin"* ]]; then
        target_dir="$HOME/Library/Fonts"
    else
        target_dir="$HOME/.local/share/fonts"
    fi

    local url sha256 tmp_dir zip_path actual_sha256
    url=$(jq -r '.["iosevka-charon"].url' "$lockfile")
    sha256=$(jq -r '.["iosevka-charon"].sha256' "$lockfile")

    tmp_dir="$(mktemp -d)"
    zip_path="${tmp_dir}/fonts.zip"

    curl -fsSL "$url" -o "$zip_path"
    actual_sha256=$(shasum -a 256 "$zip_path" | awk '{print $1}')
    if [[ "$actual_sha256" != "$sha256" ]]; then
        rm -rf "$tmp_dir"
        die "SHA256 mismatch for iosevka-charon: expected $sha256, got $actual_sha256"
    fi

    unzip -q "$zip_path" -d "$tmp_dir"
    mkdir -p "$target_dir"
    find "$tmp_dir" -name "*.ttf" -o -name "*.otf" | while read -r font; do
        cp -f "$font" "$target_dir/$(basename "$font")"
    done

    rm -rf "$tmp_dir"

    # Update font cache on Linux
    if [[ "$OSTYPE" == "linux-gnu"* ]] && command -v fc-cache &>/dev/null; then
        fc-cache -f
    fi
}

install_launchdaemon() {
    local script_src="$1" script_dst="$2" plist_src="$3" plist_dst="$4"
    cmp -s "$script_src" "$script_dst" && cmp -s "$plist_src" "$plist_dst" && return 0

    echo "Installing $(basename "$plist_src")..."
    sudo cp "$script_src" "$script_dst"
    sudo chmod +x "$script_dst"
    sudo cp "$plist_src" "$plist_dst"
    sudo launchctl load -w "$plist_dst" 2>/dev/null || true
}

install_cargo_tools() {
    echo "Installing cargo tools..."
    if command -v rustup &>/dev/null; then
        if rustup show | grep -q "no active toolchain"; then
            echo "Setting rustup default toolchain to nightly..."
            rustup default nightly
        fi
    fi
}

setup_local_rc_files() {
    local pairs=".profile:.profile.shared .bashrc:.bashrc.shared .zshrc:.zshrc.shared"

    for pair in $pairs; do
        local rc="${pair%%:*}"
        local shared="${pair#*:}"
        local target="${HOME}/${rc}"

        local env_logic='
# Source .ENV (case invariant) if it exists
if command -v find >/dev/null 2>&1; then
    _env_file=$(find "$HOME" -maxdepth 1 -iname ".env" -type f | head -n 1)
    [ -n "$_env_file" ] && . "$_env_file"
    unset _env_file
fi'

        if [[ -f "$target" ]]; then
            if ! grep -q "Source .ENV" "$target"; then
                echo "Updating ${rc}..."
                echo "$env_logic" >> "$target"
            fi
        else
            echo "Creating ${rc}..."
            cat > "$target" <<EOF
# Source shared configuration (managed by Nix Home Manager)
[ -f "\${HOME}/${shared}" ] && . "\${HOME}/${shared}"

$env_logic

# Machine-specific configuration below

EOF
        fi
    done
}

configure_os() {
    [[ "$OSTYPE" == "darwin"* ]] || return 0

    install_launchdaemon \
        ./macos/capslock_to_backspace.sh /Library/Scripts/capslock_to_backspace.sh \
        ./macos/com.capslock_to_backspace.plist /Library/LaunchDaemons/com.capslock_to_backspace.plist

    install_launchdaemon \
        ./macos/sleep_on_lid_close.sh /Library/Scripts/sleep_on_lid_close.sh \
        ./macos/com.julsh.sleeponlidclose.plist /Library/LaunchDaemons/com.julsh.sleeponlidclose.plist

    defaults write com.apple.screencapture location -string "${HOME}/Desktop"
    defaults write NSGlobalDomain AppleShowAllExtensions -bool true
    defaults write com.apple.dock show-recents -int 0
    defaults write com.apple.dock minimize-to-application -int 1
    defaults write com.apple.dock tilesize -int 34
    defaults write com.apple.dock orientation -string "left"
    killall Dock 2>/dev/null || true

    sudo defaults write /Library/Preferences/com.apple.loginwindow LoginwindowText \
        "—ฅ/ᐠ. ̫.ᐟ\\\ฅ— if it is lost, pls return this computer to lost@jul.sh"
}

install_git_hooks() {
    echo "Installing git hooks..."
    mkdir -p .git/hooks
    ln -sf ../../hooks/pre-push .git/hooks/pre-push
}

run_setup() {
    apply_nix_config
    setup_local_rc_files
    install_desktop_apps
    build_spotlight_scripts
    install_fonts
    install_cargo_tools
    install_git_hooks
    echo "Configuring OS settings (requires sudo)..."
    sudo -v
    configure_os
    echo "✓ Setup complete. Please restart your terminal for changes to take effect."
}

run_setup
