#!/usr/bin/env bash
#
# Bootstrapper for a new development environment.
#
# 1. Installs prerequisites (Homebrew, Nix)
# 2. Applies Nix Home Manager configuration
# 3. Installs GUI applications
# 4. Configures OS-level settings

set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")"

# --- Helpers ---
die() { echo "error: $1" >&2; exit 1; }

get_nix_system() {
    local os arch
    case "$OSTYPE" in
        linux-gnu*) os="linux" ;;
        darwin*)    os="darwin" ;;
        *)          die "Unsupported OS: $OSTYPE" ;;
    esac
    case "$(uname -m)" in
        x86_64)        arch="x86_64" ;;
        aarch64|arm64) arch="aarch64" ;;
        *)             die "Unsupported arch: $(uname -m)" ;;
    esac
    echo "${arch}-${os}"
}

ensure_local_host_flake() {
    mkdir -p nix/hosts/local
    cat > nix/hosts/local/flake.nix <<EOF
{
  # Machine-specific overrides (generated by setup.sh)
  outputs = { ... }: {
    homeModules.default = { lib, ... }: {
      home.homeDirectory = lib.mkForce "$HOME";
    };
  };
}
EOF
}

source_nix_profile() {
    for p in "/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh" \
             "$HOME/.nix-profile/etc/profile.d/nix.sh"; do
        [[ -f "$p" ]] && { . "$p"; return 0; }
    done
    die "Nix profile not found. Restart terminal and re-run."
}

install_nix() {
    echo "Installing Nix..."
    curl -fsSL https://install.determinate.systems/nix | sh -s -- install --determinate --no-confirm \
        || curl -L https://nixos.org/nix/install | sh -s -- --no-daemon \
        || die "Nix installation failed"
    source_nix_profile
}

# --- Setup Steps ---
install_prereqs() {
    if [[ "$OSTYPE" == "darwin"* ]]; then
        command -v brew &>/dev/null || {
            echo "Installing Homebrew..."
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        }
    elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
        if ! command -v git &>/dev/null || ! command -v curl &>/dev/null; then
            command -v apt-get &>/dev/null && {
                echo "Installing git and curl..."
                sudo apt-get update && sudo apt-get install -y git curl
            }
        fi
    else
        die "Unsupported OS: $OSTYPE"
    fi

    command -v nix &>/dev/null || install_nix
}

apply_nix_config() {
    echo "Applying Home Manager configuration..."
    ensure_local_host_flake
    # Override flaky substituters from system Nix config to stick to cache.nixos.org
    local nix_config=$'experimental-features = nix-command flakes\nsubstituters = https://cache.nixos.org/\ntrusted-substituters = https://cache.nixos.org/\n'
    local flake_ref="./nix#${USER}@$(get_nix_system)"
    local local_host_override="--override-input local-host path:./nix/hosts/local"
    NIX_CONFIG="$nix_config" \
    nix run --no-write-lock-file $local_host_override "./nix#home-manager" -- \
        switch --flake "$flake_ref" $local_host_override -b backup
}

install_desktop_apps() {
    if [[ "$OSTYPE" == "darwin"* ]]; then
        echo "Installing desktop apps..."
        brew install --cask --force raycast zed
    elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
        command -v zed &>/dev/null || {
            echo "Installing Zed..."
            curl -f https://zed.dev/install.sh | sh
        }
    fi
}

install_launchdaemon() {
    local script_src="$1" script_dst="$2" plist_src="$3" plist_dst="$4"
    cmp -s "$script_src" "$script_dst" && cmp -s "$plist_src" "$plist_dst" && return 0

    echo "Installing $(basename "$plist_src")..."
    sudo cp "$script_src" "$script_dst"
    sudo chmod +x "$script_dst"
    sudo cp "$plist_src" "$plist_dst"
    sudo launchctl load -w "$plist_dst" 2>/dev/null || true
}

install_cargo_tools() {
    echo "Installing cargo tools..."
    
    # Ensure rustup is configured if installed
    if command -v rustup &>/dev/null; then
        if rustup show | grep -q "no active toolchain"; then
            echo "Setting rustup default toolchain to nightly..."
            rustup default nightly
        fi
    fi

    # Ensure rustup/cargo is available (installed via Nix)
    if command -v cargo &>/dev/null; then
        cargo install fresh-editor
    else
        echo "Warning: cargo not found, skipping cargo tools installation"
    fi
}

setup_local_rc_files() {
    local pairs=".profile:.profile.shared .bashrc:.bashrc.shared .zshrc:.zshrc.shared"

    for pair in $pairs; do
        local rc="${pair%%:*}"
        local shared="${pair#*:}"
        local target="${HOME}/${rc}"
        
        # Logic to source .ENV (case invariant)
        local env_logic='
# Source .ENV (case invariant) if it exists
if command -v find >/dev/null 2>&1; then
    _env_file=$(find "$HOME" -maxdepth 1 -iname ".env" -type f | head -n 1)
    [ -n "$_env_file" ] && . "$_env_file"
    unset _env_file
fi'

        if [[ -f "$target" ]]; then
            if ! grep -q "Source .ENV" "$target"; then
                echo "Updating ${rc}..."
                echo "$env_logic" >> "$target"
            fi
        else
            echo "Creating ${rc}..."
            cat > "$target" <<EOF
# Source shared configuration (managed by Nix Home Manager)
[ -f "\${HOME}/${shared}" ] && . "\${HOME}/${shared}"

$env_logic

# Machine-specific configuration below

EOF
        fi
    done
}

configure_os() {
    [[ "$OSTYPE" == "darwin"* ]] || return 0

    install_launchdaemon \
        ./macos/capslock_to_backspace.sh /Library/Scripts/capslock_to_backspace.sh \
        ./macos/com.capslock_to_backspace.plist /Library/LaunchDaemons/com.capslock_to_backspace.plist

    install_launchdaemon \
        ./macos/sleep_on_lid_close.sh /Library/Scripts/sleep_on_lid_close.sh \
        ./macos/com.julsh.sleeponlidclose.plist /Library/LaunchDaemons/com.julsh.sleeponlidclose.plist

    defaults write com.apple.screencapture location -string "${HOME}/Desktop"
    defaults write NSGlobalDomain AppleShowAllExtensions -bool true
    defaults write com.apple.dock show-recents -int 0
    defaults write com.apple.dock minimize-to-application -int 1
    defaults write com.apple.dock tilesize -int 34
    defaults write com.apple.dock orientation -string "left"
    killall Dock 2>/dev/null || true

    sudo defaults write /Library/Preferences/com.apple.loginwindow LoginwindowText \
        "—ฅ/ᐠ. ̫.ᐟ\\\ฅ— if it is lost, pls return this computer to lost@jul.sh"
}

main() {
    install_prereqs
    apply_nix_config
    setup_local_rc_files
    install_desktop_apps
    install_cargo_tools
    configure_os
    echo "✓ Setup complete. Please restart your terminal for changes to take effect."
}

main
